// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdmwcgryucdqetkwoyva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkbXdjZ3J5dWNkcWV0a3dveXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MjkyNjAsImV4cCI6MjA1MzEwNTI2MH0.NrBHoYCrVR-Fdun0PVAzmk__sgkRRp1tRugu6ksTFAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);