// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjhbnqhtxylcwkfhsooq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaGJucWh0eHlsY3drZmhzb29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMDg5NDEsImV4cCI6MjA1MTg4NDk0MX0.NiODAD8mEaW5PpancKuQQ41CB-zLmIsg3j4XdyKr3QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);